### ISSUE TITLE
Diagrama de classes confuso

### ISSUE THREAD

**Issue by rafatosta** [felipe-py/Gerenciador-de-Bibliotecas#4]
Questionamentos:

- Se Leitor é uma Pessoa e Pessoa é um Funcionário, Leitor é um Funcionário? _(Revisar o conceito e aplicação de herança!)_
- Por que há duas "linhas" ligando as classes Reserva e Leitor e Empréstimo e Leitor?

Enfim, é preciso revisar todos os relacionamentos do diagrama de classes.

![image](https://github.com/felipe-py/Gerenciador-de-Bibliotecas/assets/18619894/5e67f1df-d421-4c3c-a7a8-cf7ace5801a2)

**Comment by rafatosta** [comment]
Obs.: LocalizacaoLivro e CategoriaLivro não são classes, logo não há como estabelecer um relacionamento com classes.

**Comment by Lucas-L-Rodrigues** [comment]
Novo diagrama adicionado
